<main class="bs-masthead" id="content" role="main">
    <div class="container">
        <h1>Administrador Lonera</h1>
        <br>
        <br>
        <p class="lead">Venta rápida</p>

        <!--<p>
            <a href="/order/list" class="btn btn-outline-inverse btn-lg">Ver pedidos</a>
            <a href="/public/new" class="btn btn-outline-inverse btn-lg">Crear pedido</a>


        </p>
        <p>
            <a href="/client/list" class="btn btn-outline-inverse btn-lg">Ver clientes</a>
            <a href="/public/new" class="btn btn-outline-inverse btn-lg">Crear cliente</a>
        </p>-->
        <?php if ($this->products !== FALSE): ?>
            <div class="row">
        <?php for ($i=0; $i<count($this->products); $i+=1) { ?>
                    <div class="col-sm-4" style="margin-bottom: 20px">
                        <div class="card bg-transparent text-white border-white">
                            <div class="card-body">
                                <h5 class="card-title">Tipo: <?php echo $this->products[$i]->name; ?></h5>
                                <p class="card-text">Color: <?php echo $this->products[$i]->color; ?></p>
                                <a href="#" class="btn btn-lg btn-outline-light">Crear pedido</a>
                            </div>
                        </div>
                    </div>
        <?php } ?>
                </div>
                <br>


        <?php endif; ?>
    </div>



    <div class="modal fade" id="userLoginForm">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>-->
                    <h4 class="modal-title">Log in</h4>
                </div>
                <div class="modal-body">
                    <form role="form" action="/index/login" method="POST" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="userLoginEmail">Email address</label>
                            <input type="email" class="form-control" name="userLoginEmail" id="userLoginEmail" placeholder="Enter email">
                        </div>
                        <button type="submit" class="btn btn-primary" >Login</button>
                    </form>
                </div>
                <!--<div class="modal-footer">
                    
                </div>-->
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->    
</main>

<script type="text/javascript">
    $(function() {

        if(<?=$this->not_is_valid_user?>){
        $('#userLoginForm').modal({
            backdrop: 'static',
            keyboard: false,
            show: true
        });
        }
    });

</script>