<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="#">

        <title>Administrar Lonera</title>

        <!-- Bootstrap core CSS -->
        <!--<link href="/css/bootstrap.min.css" rel="stylesheet">-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <link href="/css/docs.css" rel="stylesheet">
        
        <!-- Custom styles -->
        <link href="/css/styles.custom.css" rel="stylesheet">
        <link href="/css/bootstrap-wysihtml5.css" rel="stylesheet">
        <link href="/css/wysiwyg-color.css" rel="stylesheet">
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">


        <!--<script src="/js/jquery-1.10.2.min.js"></script>-->
        <!--<script src="/js/bootstrap.min.js"></script>-->
        <script src="/js/bootstrap-filestyle.min.js"> </script>
<!--        <script src="/js/wysihtml5-0.3.0.js"> </script>
-->        <script src="/js/bootstrap-wysihtml5.js"> </script>
        
    </head>

    <body class="<?= $this->body_class ?>">

    <header class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #563d7c; border-color: #463265;
    box-shadow: 0 1px 0 rgba(255,255,255,.1);">
        <div class="container">
        <a class="navbar-brand" href="../">Administrador Lonera</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="/order/list">Pedidos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/client/list">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/product/list">Productos</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <span class="navbar-text mail">
                    <?php echo $this->user ?>
                </span>
                <button type="button" class="btn btn-link" href="/index/logout" style="margin-left: 5px; color: white">Salir</button>
            </form>
        </div>
        </div>
    </header>
        <?php echo $this->layout()->content ?>
    </body>
    <script>
        $(function() {
            const el = $('a[href^="/' + location.pathname.split("/")[1] + '"].nav-link');
            if (el.length === 1) {
                el.addClass('active');
            }
        });
    </script>
</html>