<div class="container bs-docs-container">
    <br>
    <div class="row">
        <div class="col-sm">
            <h1>Productos</h1>
        </div>
        <div class="col-sm">
            <h1></h1>
        </div>
        <div class="col-sm">
            <a role="button" class="btn btn-primary btn-lg create-button" href="/product/new">
                Crear Producto
            </a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12" role="main">
            <div class="card">
                <!-- Default panel contents -->
                <div class="card-header">Buscar productos</div>
                <div class="card-body">
                    <form>
                        <div class="form-row align-items-center">
                            <div class="col-auto">
                                <label class="sr-only" for="inlineFormInput">Medida</label>
                                <input type="text" class="form-control mb-2" id="inlineFormInput" placeholder="Medida">
                            </div>
                            <div class="col-auto">
                                <label class="sr-only" for="inlineFormInputGroup">Color</label>
                                <input type="text" class="form-control mb-2" id="inlineFormInputGroup" placeholder="Color">
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-primary mb-2">Buscar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <br/>

            <br/>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Medida</th>
                    <th scope="col">Color</th>
                    <th scope="col">Acciones</th>
                </tr>
                </thead>
                <tbody>
                <?php if ($this->products !== FALSE): ?>
                    <?php foreach ($this->products as $key => $val): ?>
                        <tr>
                            <td scope="row"><?php echo $this->escape($val->id) ?></td>
                            <td><?php echo $val->name ?></td>
                            <td><?php echo $val->color ?></td>
                            <td>
                                <a href="#" title="Edit" onclick="editClient(<?php echo $val->id ?>);
                                            return false;" ><span class="fas fa-pencil-alt"></span></a>&nbsp;&nbsp;
                                <a href="#" title="Delete" onclick="editTkt(<?= $val->id ?>);
                                                 return false;"><span class="fas fa-trash-alt"></span></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>

            <!-- PAGINADO 
            <div style="text-align: center">
                <ul class="pagination">
                    <li class="disabled"><a href="#">&laquo;</a></li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">&raquo;</a></li>
                </ul>
            </div>
            -->


        </div>
    </div>
</div>
<!--
<span class="label label-default">Default</span>
<span class="label label-primary">Primary</span>
<span class="label label-success">Success</span>
<span class="label label-info">Info</span>
<span class="label label-warning">Warning</span>
<span class="label label-danger">Danger</span>
-->

<div class="modal fade" id="tktEditForm">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Edit ticket</h4>
            </div>
            <div class="modal-body">
                <div class="bs-callout" id="editTktPriorityClass" style="margin-top:5px">
                    <h4 id="editTktTitle" >No default class</h4>
                    <h6 id="editTktHelptopic" style="font-weight: bold"></h6>
                    <p><span id="editTktDate"></span>&nbsp;&nbsp;&nbsp;&nbsp;Priority:&nbsp;<strong><span id="editTktPriority">URGENT</span></strong>&nbsp;&nbsp;&nbsp;&nbsp;Status: <span class="label" id="editTktStatus">WAITING</span></p>
                    <div id="editTktAttached">
                    <!--<p id="editTktAttached"></p>-->
                    </div>
                    <hr/>
                    <p id="editTktDescription">Alerts don't have default classes, only base and modifier classes. A default gray alert doesn't make too much sense, so you're required to specify a type via contextual class. Choose from success, info, warning, or danger.</p>

                </div>

                <strong>Add a comment to support</strong>
                <div>&nbsp;</div>
                <form role="form" class="form-horizontal" id="form1" action="/public/savecomment" method="POST" enctype="multipart/form-data">
                    <input type="hidden" id="editFrmTktId" name="editFrmTktId" value="" />
                    <div class="form-group" id="editFrmTktCommentClass">
                        <label for="editFrmTktComment" class="col-sm-2 control-label" >Comment</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" id="editFrmTktComment" name="editFrmTktComment" rows="3" ></textarea>
                        </div>
                    </div>

                    <div id="fileupload">

                        <div class="form-group" id="fileform1">
                            <label for="inputfile1" class="col-sm-2 control-label">Upload: </label>
                            <div class="col-sm-10">
                                <input id="inputfile1" name="tktfile1" type="file" class="filestyle" >
                            </div>
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10" style="text-align:right">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="submit" id="submitbtn" class="btn btn-default btn-primary" ><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;Send &amp; close</button>
                        </div>
                    </div>
                </form>

                <div id="tktcomments">

                </div>

            </div>
            <!--<div class="modal-footer">
                
            </div>-->
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
    
    $("#form1").submit(function(event){
        
        if ($("#editFrmTktComment").val()!=""){
            $("#editFrmTktCommentClass").addClass("form-group has-success");
            document.getElementById("submitbtn").setAttribute('disabled','disabled');
            document.getElementById("form1").submit();     
        } else {
            event.preventDefault();//cancela el envio del formulario
            $("#editFrmTktCommentClass").addClass("form-group has-error");
            $("#editFrmTktComment").focus();
        }     
    });
    
       
    function setFileStyle(){
        $(":file").filestyle({
            classButton: 'btn btn-default marginLeft10',
            classIcon: 'glyphicon glyphicon-folder-open',
            classInput: 'form-control width200 pull-left'
        });
   
    }
    
    $(document).ready(function(){
        setFileStyle();
        
    });
    var last="1";
    $( "#inputfile1" ).change(function(){addNewFile()});
    
    function addNewFile(){
        if( $("#inputfile"+last).val() != ""){
            
            var div=document.createElement("div");
            $(div).attr("class","form-group");
            $(div).attr("id","fileform"+(parseInt(last)+1));
        
            var input=document.createElement("input");
        
            $(input).attr("id","inputfile"+(parseInt(last)+1));
            $(input).attr("name","tktfile"+(parseInt(last)+1));
            $(input).attr("type","file");
            $(input).attr("value","");
            $(input).attr("class","filestyle");
        
            var label=document.createElement("label");
            $(label).attr("class","col-sm-2 control-label");
            $(label).attr("for","tktfile"+(parseInt(last)+1))
            $(label).html("");
        
            var div2=document.createElement("div");
            $(div2).attr("class","col-sm-10");
        
        
            $(div).append(label);
            $(div2).append(input);
            $(div).append(div2);
        
        
            $( "#fileupload" ).append(div);
            setFileStyle();
        
        
            $( "#inputfile"+(parseInt(last)+1) ).change(function(){addNewFile()});
            last++;
        
        }
        
    }
    
    
     
    
    
    function editClient(id) {

        var uri = '/public/getclient/id/' + id;
        $.post(uri, {}, function(_data) {
           
            console.log(_data);

                                            
            if (_data.attached!=null){
                $("#editTktAttached").html("");
                for(var i=0; i < _data.attachedlink.length; i++){
                    
                    var link=document.createElement("a");
                    $(link).attr("href","/upload/"+_data.attachedlink[i]);
                    $(link).attr("target","_blank");
                
                    var fileicon=document.createElement("i");
                    $(fileicon).addClass("glyphicon glyphicon-file");
                    $(link).append(fileicon);
                    $(link).append(_data.attachedlink[i]);
                    
                    var space=document.createElement("p");
                    $(space).html(link);
                    $("#editTktAttached").append(space);
                }
            }else{
                $("#editTktAttached").html("");
            }
                                            
                                            
            $("#editFrmTktId").val(_data.id);

            $("#editTktDate").html(_data.created_date);
            $("#editTktTitle").html(_data.title);
            $("#editTktDescription").html(_data.description);
            $("#editTktHelptopic").html(_data.helptopic);
            $("#editTktPriority").html(_data.priority);
            $("#editTktStatus").html(_data.status);
            $("#editTktStatus").addClass(_data.statusclass);

            $("#editTktPriorityClass").attr('class', '');
            if (_data.priorityclass !== '') {

                $("#editTktPriorityClass").addClass('bs-callout bs-callout-' + _data.priorityclass);
            }
            else {
                $("#editTktPriorityClass").addClass('bs-callout bs-callout-info');
            }

            $("#tktcomments").html("");
            for(var i=0; i < _data.comments.length; i++){
                                                
                var title = document.createElement("strong");
                var date = document.createElement("small");
                var comment = document.createElement("p");
                var container = document.createElement("div");
                                                
                //$(container).addClass('alert alert-info');
                $(container).css("margin-bottom","5px");
                                                
                if( Number(_data.comments[i].is_support_user) === 1 ){
                    $(container).addClass("text-primary");
                }
                                                
                $(title).html( _data.comments[i].author + ' ' );
                $(date).html( _data.comments[i].created_date );
                $(comment).html( _data.comments[i].comment );
                                                
                $(title).append(date);
                                                
                $(container).append(title).append(comment);
                $("#tktcomments").append(container);
                                             
            }

            //<h4 class="media-heading">sarrubia@gmail.com <small>2013-10-01</small></h4>
            //<p>Un comentario largo Un comentario largo Un comentario largo Un comentario largo Un comentario largo Un comentario largo Un comentario largo Un comentario largo </p>


            $('#tktEditForm').modal({
                backdrop: 'static',
                keyboard: false,
                show: true
            });

        }, 'json');

    }
</script>