
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-12">
            <h1>New ticket</h1>
            <p>Please provide as much detail as possible so we can best assist you. To update a previously submitted ticket, please go to <a href="/public/list">view my tickets</a>.</p>
            <br/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">&nbsp;</div>
        <div class="col-md-8" role="main">
            <form id="form1" class="form-horizontal" role="form" action="/public/add" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="tktTitle" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="tktTitle" name="tktTitle" placeholder="Enter the ticket title">
                    </div>
                </div>
                <div class="form-group">
                    <label for="tktDescription" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="tktDescription" name="tktDescription" rows="8" placeholder="Enter the ticket description"></textarea>
                        <span class="help-block">Please provide as much detail as possible so we can best assist you.</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="tktHelpTopic" class="col-sm-2 control-label">Help topic</label>
                    <div class="col-sm-10">
                        <select name="tktHelpTopic" id="tktProject" class="form-control">
                            <option value="0">-- Select project --</option>
                            <?for( $this->helptopics->rewind(); $this->helptopics->valid(); $this->helptopics->next() ):?>
                                <option value="<?=$this->helptopics->current()->id?>"><?=$this->helptopics->current()->title?></option>
                            <?endfor;?>
                            
                        </select>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="tktPriority" class="col-sm-2 control-label">Priority</label>
                    <div class="col-sm-10">
                        <select name="tktPriority" id="tktPriority" class="form-control">
                            <option value="0">-- Ticket priority --</option>
                            <option value="1">LOW</option>
                            <option value="2">NORMAL</option>
                            <option value="3">HIGH</option>
                            <option value="4">URGENT</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label for="tktFile" class="col-sm-2 control-label">File Upload</label>
                    <div class="col-sm-10">
                      <input name="tktfile1" type="file" class="filestyle" >
                    </div>
                </div>
                <hr>
                <div class="form-group pull-right">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button id="submitbtn" type="submit" class="btn btn-primary" onclick="buttonDisable()"><span class="glyphicon glyphicon-save" ></span>&nbsp;Save</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-2">&nbsp;</div>
    </div>
</div>

<script type="text/javascript">
    function buttonDisable(){
        document.getElementById("submitbtn").setAttribute('disabled','disabled');
        document.getElementById("form1").submit();     
    }
$(function(){
   $(":file").filestyle({
       classButton: 'btn btn-default marginLeft10',
       classIcon: 'glyphicon glyphicon-folder-open',
       classInput: 'form-control width200 pull-left'
   });
   $('textarea').wysihtml5({"stylesheets": ["/css/wysiwyg-color.css"],
                "font-styles" : false,
                "image" : false,
                "color" : true,
                "html" : false
                }); 
  
});




</script>
