<div class="container bs-docs-container">
    <br>

    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-4">
            <h1>Nuevo pedido</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">&nbsp;</div>
        <div class="col-sm-8" role="main">
            <form id="form1" class="form-horizontal" role="form" action="/public/add" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="tktTitle" class="col-sm-2 control-label">Total en $</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="tktTitle" name="tktTitle" placeholder="$">
                    </div>
                </div>
                <div class="form-group">
                    <label for="tktHelpTopic" class="col-sm-2 control-label">Producto</label>
                    <div class="col-sm-10">
                        <select name="tktHelpTopic" id="tktProject" class="form-control">
                            <option value="0">Elegir producto...</option>
                            <?php foreach ($this->products as $key => $val): ?>
                                <option value="<?php echo $val->id;?>"><?php echo $val->name . ' - ' . $val->color;?></option>
                            <?php endforeach; ?>
                            
                        </select>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="tktPriority" class="col-sm-2 control-label">Cliente</label>
                    <div class="col-sm-10">
                        <select name="tktPriority" id="tktPriority" class="form-control">
                            <option value="0">Elegir Cliente...</option>
                            <option value="1">LOW</option>
                            <option value="2">NORMAL</option>
                            <option value="3">HIGH</option>
                            <option value="4">URGENT</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-10">
                        <textarea class="form-control" id="tktDescription" name="tktDescription" rows="4" placeholder="Ingresa cualquier info extra..."></textarea>
<!--                        <span class="help-block">Please provide as much detail as possible so we can best assist you.</span>
-->                    </div>
                </div>

                <div class="form-group col-sm-4">
                      <label for="tktFile">Subir archivo</label>
                      <input name="tktfile1" type="file" class="form-control-file">
                </div>
                <hr>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button id="submitbtn" type="submit" class="btn btn-primary" onclick="buttonDisable()"><span class="fas fa-save" ></span>&nbsp;Guardar</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-2">&nbsp;</div>
    </div>
</div>

<script type="text/javascript">
    function buttonDisable(){
        document.getElementById("submitbtn").setAttribute('disabled','disabled');
        document.getElementById("form1").submit();     
    }
$(function(){
   $(":file").filestyle({
       classButton: 'btn btn-default',
       classIcon: 'fas fa-folder-open',
       classInput: 'form-control'
   });
  
});

</script>
