<div class="container bs-docs-container">
    <br>

    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-4">
            <h1>Nuevo pedido</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-2">&nbsp;</div>
        <div class="col-sm-8" role="main">
            <form id="form1" class="form-horizontal" role="form" action="/order/add" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="client" class="col-sm-2 control-label">Cliente</label>
                    <div class="col-sm-10">
                        <select name="client" id="client" class="selectpicker form-control" data-live-search="true">
                            <option value="0">Elegir...</option>
                            <?php foreach ($this->clients as $key => $val): ?>
                                <option value="<?php echo $val->id;?>"><?php echo $val->name;?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="total" class="col-sm-3 control-label">Total del pedido</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="total" name="total" placeholder="$">
                    </div>
                </div>
                <div class="form-group">
                    <label for="paid_total" class="col-sm-3 control-label">Total pagado</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="paid_total" name="paid_total" placeholder="$">
                    </div>
                </div>
                <div class="form-group">
                    <label for="payment_method" class="col-sm-3 control-label">Forma de pago</label>
                    <div class="col-sm-10" >
                        <select id="payment_method" class="form-control"  name="payment_method">
                            <option>Efectivo</option>
                            <option>Cheque</option>
                        </select>
                    </div>
                </div>

                <div class="form-group datepicker">
                    <label for="check_date" class="col-sm-3 control-label">Fecha cheque</label>
                    <div class="col-sm-10">
                        <input name="check_date" id="check_date" type="text" class="form-control" data-date-format="dd/mm/yyyy">
                    </div>
                </div>
                <div class="form-group">
                    <label for="product" class="col-sm-2 control-label">Producto</label>
                    <div class="col-sm-10">
                        <select name="type_id" id="type_id" class="selectpicker form-control" data-live-search="true">
                            <option value="0">Elegir producto...</option>
                            <?php foreach ($this->products as $key => $val): ?>
                                <option value="<?php echo $val->id;?>"><?php echo $val->name . ' - ' . $val->color;?></option>
                            <?php endforeach; ?>
                            
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="meters" class="col-sm-3 control-label">Metros lineales</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="meters" name="meters" placeholder="Mts">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-10">
                        <textarea class="form-control" id="description" name="description" rows="4" placeholder="Ingresa cualquier info extra..."></textarea>
<!--                        <span class="help-block">Please provide as much detail as possible so we can best assist you.</span>
-->                    </div>
                </div>

                <!--<div class="form-group col-sm-4">
                      <label for="tktFile">Subir archivo</label>
                      <input name="tktfile1" type="file" class="form-control-file">
                </div>-->
                <hr>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button id="submitbtn" type="submit" class="btn btn-primary" onclick="buttonDisable()"><span class="fas fa-save" ></span>&nbsp;Guardar</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-2">&nbsp;</div>
    </div>
</div>

<script type="text/javascript">
    function buttonDisable(){
        document.getElementById("submitbtn").setAttribute('disabled','disabled');
        document.getElementById("form1").submit();     
    }
$(function(){
    $('.datepicker input').datepicker({language: 'es'});

    $('#payment_method').change(function(){
       if ($(this).val() === 'Cheque')  {
           $('.datepicker').show();
       } else {
           $('.datepicker').hide();
       }
    });
    $('#payment_method').trigger('change');
   $(":file").filestyle({
       classButton: 'btn btn-default',
       classIcon: 'fas fa-folder-open',
       classInput: 'form-control'
   });
  
});

</script>
