

<!-- Button trigger modal 
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>-->
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-12">
            <h1>Create New Support User</h1>
            <p>Complete information to create new support user.</p>
            <br/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">&nbsp;</div>
        <div class="col-md-8" role="main">
            <form class="form-horizontal" role="form" action="/admin/adduser" method="POST" >
                <? if ($this->user_exists): ?>
                <div class="form-group has-error">
                <? else: ?>
                <div class="form-group">
                <? endif ?>
                        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                            <input name="email" type="email" class="form-control" autofocus="autofocus" id="inputEmail" placeholder="Email">
                            <? if ($this->user_exists): ?>
                            <span class="help-block spancolor">El email existe</span>
                            <? endif ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                        <div class="col-sm-10">
                            <input name="password" type="password" class="form-control" id="inputPassword3" placeholder="Password">
                        </div>
                    </div>
                    <? if ($this->pass_mismatch): ?>
                        <div class="form-group has-error">
                        <? else: ?>
                            <div class="form-group">
                            <? endif ?>
                            <label for="inputPassword4" class="col-sm-2 control-label">Confirm Password</label>
                            <div class="col-sm-10">
                                <input name="passwordconfirm" type="password" class="form-control" id="inputPassword4" placeholder="Re-Enter Password">
                            </div>
                        </div>

                        <hr>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary pull-right">Create User</button>
                            </div>
                        </div>

                        </form>
                    </div>
                    <div class="col-md-2">&nbsp;</div>
                </div>
        </div>

