<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-12">
            <h1>Tickets</h1>
            <br/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" role="main">

            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">Filter your tickets</div>
                <div class="panel-body">
                    <form class="form-inline" role="form">
                        <div class="form-group">
                            <label class="sr-only" for="tktid">Ticket #</label>
                            <input type="text" class="form-control" id="tktid" name="tktid" placeholder="Ticket #">
                        </div>
                        <div class="form-group">
                            <label class="sr-only" for="tktstatus">Status</label>
                            <select name="tktstatus" id="tktstatus" class="form-control">
                                <option value="0">-- Ticket status --</option>
                                <option value="<?= Mod_Status::WAITING ?>" <?= $this->selected_status_1 ?>>WAITING</option>
                                <option value="<?= Mod_Status::IN_PROGRESS ?>" <?= $this->selected_status_2 ?>>IN PROGRESS</option>
                                <option value="<?= Mod_Status::RESOLVED ?>" <?= $this->selected_status_3 ?>>RESOLVED</option>
                                <option value="<?= Mod_Status::CLOSED ?>" <?= $this->selected_status_4 ?>>CLOSED</option>
                                <option value="<?= Mod_Status::REJECTED ?>" <?= $this->selected_status_5 ?>>REJECTED</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="sr-only" for="tktpriority">Priority</label>
                            <select name="tktpriority" id="tktpriority" class="form-control">
                                <option value="0">-- Ticket priority --</option>
                                <option value="<?= Mod_Priority::LOW ?>" <?= $this->selected_priority_1 ?>>LOW</option>
                                <option value="<?= Mod_Priority::NORMAL ?>" <?= $this->selected_priority_2 ?>>NORMAL</option>
                                <option value="<?= Mod_Priority::HIGH ?>" <?= $this->selected_priority_3 ?>>HIGH</option>
                                <option value="<?= Mod_Priority::URGENT ?>" <?= $this->selected_priority_4 ?>>URGENT</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="sr-only" for="tkthelptopic">HelpTopic</label>
                            <select name="tkthelptopic" id="tkthelptopic" class="form-control">
                                <option value="0">-- Ticket Help Topic --</option>
                                <? for ($this->helptopics->rewind(); $this->helptopics->valid(); $this->helptopics->next()): ?>
                                        <option value="<?= $this->helptopics->current()->id ?>"   
                                            <? if($this->selectHelpTopic == $this->helptopics->current()->id): ?>
                                            selected="selected"
                                            <?endif?>
                                            ><?= $this->helptopics->current()->title ?></option>
                                <? endfor; ?>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Apply</button>
                    </form>
                </div>
            </div>
            <br/>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Priority</th>
                        <th>Status</th>
                        <th>Created</th>
                        <th>Updated</th>
                        <th>User</th>
                        <th>Support User</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>

                    <? for ($this->tickets->rewind(); $this->tickets->valid(); $this->tickets->next()): ?>
                        <tr class="<?= Mod_Priority::getPriorityViewClass($this->tickets->current()->priority) ?>">
                            <td><?= $this->tickets->current()->id ?></td>
                            <td><?= $this->tickets->current()->title ?></td>
                            <td><?= Mod_Priority::getPriorityName($this->tickets->current()->priority) ?></td>
                            <td><span class="label <?= Mod_Status::getStatusViewClass($this->tickets->current()->status) ?>"><?= Mod_Status::getStatusName($this->tickets->current()->status) ?></span></td>
                            <td><?= $this->tickets->current()->created_date ?></td>
                            <td><?= $this->tickets->current()->updated_date ?></td>
                            <td><?= $this->tickets->current()->created_user ?></td>
                            <td><?= $this->tickets->current()->support_user ?></td>
                            <td>
                    <center> <a href="#" title="Edit" onclick="javascript:editTkt(<?= $this->tickets->current()->id ?>);
                        return false;" ><span class="glyphicon glyphicon-pencil"></span></a>&nbsp;&nbsp; <center/>
                <!--    <a href="#" title="Close" onclick="javascript:editTkt(<?= $this->tickets->current()->id ?>);
                                return false;"><span class="glyphicon glyphicon-remove"></span></a> -->
                        </td>
                        </tr>
                    <? endfor; ?>
                    </tbody>
            </table>
            <br/>
            <!-- PAGINADO -->
            <div style="text-align: center">
                <ul class="pagination">
                    <li <? if($this->selectedpage==1):?>
                        class="disabled"
                        <?endif?>
                        ><a href="<?=$this->first?>">&laquo; First</a></li>
                    
                    <li <? if($this->selectedpage==1):?>
                        class="disabled"
                        <?endif?>
                        ><a href="<?= $this->prev?>">&LT; Previous</a></li>
                    
                    <li class="disabled"><a href="#"> Page <?=$this->selectedpage?> of <?=$this->cantpaginas?></a></li>
                    
                    <li <? if($this->selectedpage==$this->cantpaginas):?>
                        class="disabled"
                        <?endif?>
                        ><a href="<?=$this->next?>">&GT; Next</a></li>
                    
                    <li <? if($this->selectedpage==$this->cantpaginas):?>
                        class="disabled"
                        <?endif?>
                        ><a href="<?= $this->last?>">&raquo; Last</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!--
<span class="label label-default">Default</span>
<span class="label label-primary">Primary</span>
<span class="label label-success">Success</span>
<span class="label label-info">Info</span>
<span class="label label-warning">Warning</span>
<span class="label label-danger">Danger</span>
-->

<div class="modal fade" id="tktEditForm">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Edit ticket </h4>
            </div>
            <div class="modal-body">
                <div class="bs-callout" id="editTktPriorityClass" style="margin-top:5px">
                    <h4 id="editTktTitle" >No default class</h4>
                    <h6 id="editTktHelptopic" style="font-weight: bold"></h6>
                    <p><span id="editTktDate"></span>&nbsp;&nbsp;&nbsp;&nbsp;Priority:&nbsp;<strong><span id="editTktPriority">URGENT</span></strong>&nbsp;&nbsp;&nbsp;&nbsp;Status: <span class="label" id="editTktStatus">WAITING</span></p>
                    <p id="editTktAttached"></p>
                    <hr/>

                    <p id="editTktDescription">Alerts don't have default classes, only base and modifier classes. A default gray alert doesn't make too much sense, so you're required to specify a type via contextual class. Choose from success, info, warning, or danger.</p>

                </div>

                <strong>Support</strong>
                <div>&nbsp;</div>
                <form role="form" class="form-horizontal" action="/admin/savetkt" method="POST" enctype="multipart/form-data">
                    <input type="hidden" id="editFrmTktId" name="editFrmTktId" value="" />
                    
                    <div class="form-group">
                        <label for="editFrmTktStatus" class="col-sm-2 control-label">Status</label>
                        <div class="col-sm-10">
                            <select name="editFrmTktStatus" id="editFrmTktStatus" class="form-control">
                                <option value="0">-- Ticket status --</option>
                                <option value="<?= Mod_Status::WAITING ?>">WAITING</option>
                                <option value="<?= Mod_Status::IN_PROGRESS ?>" >IN PROGRESS</option>
                                <option value="<?= Mod_Status::RESOLVED ?>" >RESOLVED</option>
                                <option value="<?= Mod_Status::CLOSED ?>" >CLOSED</option>
                                <option value="<?= Mod_Status::REJECTED ?>" >REJECTED</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="editFrmTktPriority" class="col-sm-2 control-label">Priority</label>
                        <div class="col-sm-10">
                            <select name="editFrmTktPriority" id="editFrmTktPriority" class="form-control">
                                <option value="0">-- Ticket priority --</option>
                                <option value="<?= Mod_Priority::LOW ?>" >LOW</option>
                                <option value="<?= Mod_Priority::NORMAL ?>" >NORMAL</option>
                                <option value="<?= Mod_Priority::HIGH ?>" >HIGH</option>
                                <option value="<?= Mod_Priority::URGENT ?>" >URGENT</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="editFrmTktHelpTopic" class="col-sm-2 control-label">HelpTopic</label>
                        <div class="col-sm-10">
                            <select name="editFrmTktHelpTopic" id="editFrmTktHelpTopic" class="form-control">
                                <option value="0">-- Ticket Help Topic --</option>
                                <? for ($this->helptopics->rewind(); $this->helptopics->valid(); $this->helptopics->next()): ?>
                                    <option value="<?= $this->helptopics->current()->id ?>" label="<?= $this->helptopics->current()->title ?>" ></option>
                                <? endfor; ?>

                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="editFrmTktComment" class="col-sm-2 control-label">Comment</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" id="editFrmTktComment" name="editFrmTktComment" rows="3" ></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10" style="text-align:right">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-default btn-primary"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;Send &amp; close</button>
                        </div>
                    </div>
                </form>

                <div id="tktcomments">

                </div>

            </div>
            <!--<div class="modal-footer">
                
            </div>-->
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">

    function editTkt(id) {
        
        var uri = '/admin/gettkt/id/' + id;
        $.post(uri, {}, function(_data) {

            console.log(_data);

                                            
            if (_data.attached!=null){
                
                var link=document.createElement("a");
                $(link).attr("href",_data.attachedlink);
                $(link).attr("target","_blank");
                var fileicon=document.createElement("i");
                $(fileicon).addClass("glyphicon glyphicon-file");
                $(link).append(fileicon);
                $(link).append(_data.attached);
                $("#editTktAttached").html(link);
            }else{
                $("#editTktAttached").html("");
            }
                                            
            $("#editFrmTktId").val(_data.id);
            $("#editTktDate").html(_data.created_date);
            $("#editTktTitle").html(_data.title);
            $("#editTktDescription").html(_data.description);
            $("#editTktHelptopic").html(_data.helptopic);
            $("#editFrmTktHelpTopic").val(_data.id_helptopic);
            $("#editTktPriority").html(_data.priority);
            $("#editTktStatus").html(_data.status);
            $("#editTktStatus").addClass(_data.statusclass);
                                            
            $("#editTktPriorityClass").attr('class', '');
            if (_data.priorityclass !== '') {

                $("#editTktPriorityClass").addClass('bs-callout bs-callout-' + _data.priorityclass);
            }
            else {
                $("#editTktPriorityClass").addClass('bs-callout bs-callout-info');
            }

            $("#editFrmTktPriority").val(_data.priorityvalue);
            $("#editFrmTktStatus").val(_data.statusvalue);

            $("#tktcomments").html("");
            for(var i=0; i < _data.comments.length; i++){
                                                
                var title = document.createElement("strong");
                var date = document.createElement("small");
                var comment = document.createElement("p");
                var container = document.createElement("div");
                                                
                //$(container).addClass('alert alert-info');
                $(container).css("margin-bottom","5px");
                if( Number(_data.comments[i].is_support_user) === 1 ){
                    $(container).addClass("text-primary");
                }
                                                
                $(title).html( _data.comments[i].author + ' ' );
                $(date).html( _data.comments[i].created_date );
                $(comment).html( _data.comments[i].comment );
                                                
                $(title).append(date);
                                                
                $(container).append(title).append(comment);
                $("#tktcomments").append(container);
                                             
            }

            //<h4 class="media-heading">sarrubia@gmail.com <small>2013-10-01</small></h4>
            //<p>Un comentario largo Un comentario largo Un comentario largo Un comentario largo Un comentario largo Un comentario largo Un comentario largo Un comentario largo </p>


            $('#tktEditForm').modal({
                backdrop: 'static',
                keyboard: false,
                show: true
            });

        }, 'json');

    }
</script>